[project]
name = "pysenpai_sql"
version = "0.4"

[build-system]
requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
exclude = ["sql_tests", "tests", "utils"]


[tool.setuptools.package-data]
"pysenpai_sql.msg_data" = ["*/messages.yml"]
